### ISSUE TITLE
How to edit the shop gui ???

### ISSUE THREAD

**Issue by pnv28** [divios/DailyShopIssues#1]
So I am trying to make the daily shop special and clean, so players don't compare `/shop` with `/dshop open Daily_Shop` .  
I did read the [Docs](https://diviosx.gitbook.io/daily-random-shop/) but couldn't understand how it works, Can you help me ????

*Note I am using the free version*

**Comment by divios** [comment]
Hi! The first thing to note is that the customize feature on the free version is limited. In only allows the users to edit the size of the shop, the title and add/remove empty slots. The rest of the features (add items) is only available on the premium version.

**Comment by pnv28** [comment]
thx for telling, as I was kinda confused looking at the customize menu. btw Great Plugin/ :)
