### ISSUE TITLE
Rarities Not working 

### ISSUE THREAD

**Issue by SNokerYT** [divios/DailyShopIssues#2]
Rarities Not working 
1 -  i add 9 different items on a shop with Mythic Rarities
2 - i changed the shop timer to 55 seconds 
3 - i opened the shop /dailyshop open ruby
4 - all the items still on the shop Rarities not working | i think they should appear and disappear it depends on Rarities but even with Mythic not working i think it's a bug
5 - i tried the free version and premium version all the same 
![advancedenchants3fw](https://user-images.githubusercontent.com/68678154/130359276-bfd141fa-8706-40a9-92d5-77c8233adec4.gif)

**Comment by divios** [comment]
hi! This is really common misunderstanding, it is covered here https://diviosx.gitbook.io/daily-random-shop/frequently-asked-questions
